#                                                                        #
# Configuration for the TYPO3 Flow Framework                             #
#                                                                        #
# This file contains additions to the base configuration for the TYPO3   #
# Flow Framework when it runs in Testing context.                        #
#                                                                        #
# Don't modify this file - instead put your own additions into the       #
# global Configuration directory and its sub directories.                #
#                                                                        #

TYPO3:

  Flow:

    error:
      exceptionHandler:
        className: 'Famelo\PhpError\PhpErrorHandler'
